### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [luisbocanegra/substratum-tweaks#2]
The APK at tag v1.1.0 identifies as v1.0.0:

    package: name='com.luisbocanegra.substweaks' versionCode='100' versionName='1.0.0'

Looks like you forgot to update that [in the `build.gradle.kts`](https://github.com/luisbocanegra/substratum-tweaks/blob/main/app/build.gradle.kts#L41). Maybe you wish to fix that (and replace the APK by a fixed one)?

**Comment by luisbocanegra** [comment]
Oh, thank you for pointing this out, will update it as soon as I can

**Comment by luisbocanegra** [comment]
Done

**Comment by IzzySoft** [comment]
Thanks! And Btw: I've just made your app available [via my repo](https://apt.izzysoft.de/fdroid/index/apk/com.luisbocanegra.substweaks) (for users of one of the many F-Droid clients). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to point there if you like.

One last question: if I remember correctly, at least in the past Substratum required root. Is that the same with your app (root required)?

**Comment by luisbocanegra** [comment]
> Thanks! And Btw: I've just made your app available [via my repo](https://apt.izzysoft.de/fdroid/index/apk/com.luisbocanegra.substweaks) (for users of one of the many F-Droid clients). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to point there if you like.

Thank you, I will add it.
> 
> One last question: if I remember correctly, at least in the past Substratum required root. Is that the same with your app (root required)?

Yes, the apps to install and manage the "overlays" in this app (Substratum or Substratum Lite) need root to work.

**Comment by IzzySoft** [comment]
> Thank you, I will add it.

Thanks! I see it's already there :star_struck: 

> Yes, the apps (Substratum or Substratum Lite) to install and manage the "overlays" in this app need root to work.

Oops… I missed the dependencies. I knew there was something (it's many years ago I last played with Substratum, apologies). So I shall add that to the app's description then… Done.

PS: If you'd like the description etc. in [fastlane format](https://gitlab.com/-/snippets/1895688) so you can adjust it to your liking, just let me know and I'll send it over as PR (from what I've set up in my repo).

**Comment by luisbocanegra** [comment]
> PS: If you'd like the description etc. in [fastlane format](https://gitlab.com/-/snippets/1895688) so you can adjust it to your liking, just let me know and I'll send it over as PR (from what I've set up in my repo).

Yes, that will be cool!

**Comment by IzzySoft** [comment]
There you go :smiley:
